---
functional:
  - Пользователь должен иметь возможность видеть на странице товара, что
    выводится название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возможность видеть на странице каталога, что
    выводится название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге
    после добавления в корзину
  - Пользователь должен иметь возможность на странице корзины удалить товар из
    корзины
  - Пользователь должен иметь возможность на странице корзины продолжить
    выбирать товары в каталоге
  - Пользователь должен иметь возможность на странице корзины оформить заказ с
    переходом на страницу оплаты
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
  - Пользователь может просматривать каталог товаров, фильтруя их и пользуясь постраничным выводом
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен хранить корзину в сессии браузера
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
  - Ключевой возможностью магазина должна быть адаптивная верстка, чтобы он был удобным на мобильных устройствах
  - Корзина должна хранится в сессии браузера
implicit:
  - При смене английского языка на русский сайт должен переводить описание и категорию товаров
  - Поиск товара по названию и категориям должен осуществляться по всему сайту, а не только на текущей странице
  - Пользователь может на странице товара выбирать фото товара, и оно должно открываться в полномасштабном формате
  - При оформлении заказа количество товаров должно уменьшаться
  - Поиск товара должен идти не только по названию товара, но и по его производителю
  - Поиск товара по цене должен идти с учетом скидки
  - После обновления страницы на сервере должен сохраняться выбранный язык
