---
functional:
  - Пользователь должен иметь возоможность видеть на странице товара, что
    выводится название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возоможность видеть на странице каталога, что
    выводится название, рейтинг, цена со скидкой и без
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге
    после добавления в корзину
  - Пользователь должен иметь возможность на странице корзины удалить товар из
    корзины
  - Пользователь должен иметь возможность на странице корзины продолжить
    выбирать товары в каталоге
  - Пользователь должен иметь возможность на странице корзины оформить заказ с
    переходом на страницу оплаты
  - Пользователь должен иметь возможность искать товары по ключевому слову или
    категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать
    подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и
    просматривать содержимое корзины
non-functional:
  - Веб-сайт должен быть разработан с учетом удобства использования и
    оптимизирован для скорости работы.
  - Сайт должен иметь мобильную версию.
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Сайт должен хранить корзину в сессии браузера
  - Сайт должен быть протестирован на совместимость с последними версиями
    браузеров.
  - Сайт должен быть способен обрабатывать большое количество трафика
  - Сайт должен быть доступен на различных устройствах
implicit:
  - Пользователь должен иметь возможность зарегистрироваться на сайте
  - Пользователь должен иметь возможность авторизироваться на сайте
  - Пользователь должен иметь возможность выбрать регион доставки
  - Пользователь должен иметь возможность отслеживать статус своего заказа на
    сайте
  - Пользователь должен иметь возможность отказаться от заказа после его
    оформления
  - Пользователь должен иметь возможность обратиться в службу поддержки по своим
    вопросам
  - При смене английского языка на русский сайт должен переводить описание
    товаров
